#!/usr/bin/env bash
# Injects the "Latest State" section of AGENTS.md into the prompt context.
# Claude Code's UserPromptSubmit hook pipes this stdout into the prompt, so the
# most recent session writedown is seen before every message — a deterministic
# cold-start that does not depend on the agent remembering to call read_memo.
#
# AGENTS.md is generated by the write_session tool (format: 2). Its "Latest
# State" section is the newest writedown; we inject from that heading up to the
# next "## " heading (the Sessions index).

REPO_PATH="${CLAUDE_PROJECT_DIR:-$(pwd)}"
AGENTS_FILE="$REPO_PATH/AGENTS.md"

if [ ! -f "$AGENTS_FILE" ]; then
  exit 0
fi

# Print the Latest State section only: from "## Latest State" until the next
# top-level "## " heading, dropping the heading lines themselves.
CONTEXT=$(awk '
  /^## Latest State[[:space:]]*$/ { capture = 1; next }
  capture && /^## / { capture = 0 }
  capture { print }
' "$AGENTS_FILE" | sed '/^[[:space:]]*$/d')

if [ -z "$CONTEXT" ]; then
  exit 0
fi

cat <<EOF
<agent_memory>
Latest shared-memory writedown for this project (from AGENTS.md). Use it to
resume prior work and avoid repeating decisions. Run /readmemo for full history.

$CONTEXT
</agent_memory>
EOF
